{
  "hash": "5ac9e5368a126fbb7d8d704794440b5e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modeling the Syndemic Burden of Nutritional, Reproductive, and Healthcare-Access Risks Among Women in Bangladesh\"\nsubtitle: \"Evidence from the Bangladesh Demographic and Health Survey 2022\"\nauthor: \"Mukarram Hosain\"\ndate: \"May 2026\"\n---\n\n\n\n## Abstract\n\n::: {.abstract-box}\n**Background.** Women in Bangladesh experience overlapping nutritional, reproductive-health, and healthcare-access constraints. A syndemic lens is useful when such risks cluster within socially patterned contexts, but empirical claims require more than a simple count of co-occurring conditions.\n\n**Objective.** This study estimated the burden, clustering, and social patterning of co-occurring risks among women aged 15–49 using BDHS 2022.\n\n**Methods.** Nine binary indicators were grouped into nutritional, reproductive-health, and healthcare-access/autonomy domains. The primary outcome was the cumulative syndemic-burden score (range 0–9; observed 0–8), analyzed using survey-weighted quasi-Poisson regression and reported as incidence rate ratios (IRR). Ordinal logistic regression (low/medium/high burden) was used as a sensitivity analysis. All models incorporated BDHS sampling weights, primary sampling units, and strata.\n\n**Results.** Among 11,657 women with recent births, 24.0% had a score of 0, 64.6% scored 1–3, and 11.4% scored ≥4 (high burden). Any reproductive-health risk affected 57.6% of women and any access/autonomy risk affected 73.8%. All three risk domains co-occurred more than expected under independence (observed/expected ratio 1.23). In the full quasi-Poisson model, higher respondent education (IRR 1.00 reference), rural residence (IRR 1.11, 95% CI 1.06–1.16), and lower wealth were associated with elevated burden, while working women had lower scores (IRR 0.94, 95% CI 0.91–0.98). Ordinal sensitivity results were directionally consistent.\n\n**Conclusion.** The findings support a socially patterned cumulative-burden interpretation. Evidence for clustering is present, but the report avoids claiming definitive causal or biological synergy because the analysis is cross-sectional and lacks a downstream health outcome independent of the component risks.\n:::\n\n## Study Snapshot\n\n::: {.metric-grid}\n::: {.metric}\n[11,657]{.metric-value}\n[women in analytic sample]{.metric-label}\n:::\n\n::: {.metric}\n[11.4%]{.metric-value}\n[high burden, score ≥4]{.metric-label}\n:::\n\n::: {.metric}\n[1.23]{.metric-value}\n[observed/expected ratio, all 3 domains co-occurring]{.metric-label}\n:::\n\n::: {.metric}\n[IRR 1.11]{.metric-value}\n[rural vs urban, quasi-Poisson full model]{.metric-label}\n:::\n\n::: {.metric}\n[IRR 2.06]{.metric-value}\n[no education vs higher education]{.metric-label}\n:::\n\n::: {.metric}\n[IRR 1.39]{.metric-value}\n[poorest vs richest wealth quintile]{.metric-label}\n:::\n:::\n\n## Introduction\n\nSyndemic theory describes the clustering and interaction of health problems under harmful social conditions [@singer2017syndemics; @mendenhall2017ncd]. The key distinction is that a syndemic is not merely multimorbidity. A defensible syndemic analysis should show clustering, identify social or structural drivers, and assess whether co-occurrence appears greater or more consequential than expected from independent risks [@tsai2018syndemics; @bulled2024guide].\n\nBangladesh is a strong setting for this framework because women's health is shaped by intersecting nutritional vulnerability, early and high-parity reproduction, barriers to maternal healthcare, and constraints on decision-making autonomy. BDHS 2022 provides nationally representative data on women of reproductive age, household socioeconomic position, reproductive history, maternal service use, and healthcare access constraints [@niport2024bdhs; @worldbank2024bdhsmetadata].\n\nPrior Bangladesh evidence shows persistent socioeconomic inequalities in women's undernutrition [@rahman2022undernutrition; @hossain2023doubleburden; @rahman2019doubleburden], geographic and wealth gradients in nutritional burden across Southeast Asia [@biswas2022southeastasia], and strong links between child marriage, adolescent motherhood, education, residence, and partner characteristics [@islam2021childmarriage; @unicef2025childmarriage; @who2024adolescentpregnancy]. Maternal healthcare studies similarly show that institutional delivery, antenatal care, and the continuum of care are patterned by wealth, education, residence, and women's autonomy [@chakraborty2003maternal; @yaya2017delivery; @kamal2015institutional; @kamal2015skilledbirth; @khan2020urban; @khan2022continuum; @haider2017autonomy]. This study brings these strands together by modeling co-occurring risks as a cumulative burden.\n\n### Study Aims\n\n1. Estimate the weighted prevalence of individual risk factors and cumulative burden.\n2. Assess whether nutritional, reproductive-health, and access/autonomy domains cluster more than expected under independence.\n3. Identify sociodemographic predictors of elevated burden using survey-weighted quasi-Poisson regression.\n4. Evaluate robustness with ordinal logistic and cutoff sensitivity analyses.\n\n## Conceptual Framework\n\n```{mermaid}\ngraph LR\n    A[\"STRUCTURAL DRIVERS<br>Socioeconomic status<br>Education opportunities<br>Residence and Geography<br>Policy environment\"]\n    B[\"SOCIAL ENVIRONMENT<br>Employment status<br>Household dynamics<br>Healthcare quality<br>Gender-based autonomy\"]\n    C[\"PATHWAYS<br>Nutritional intake<br>Reproductive timing<br>Birth spacing<br>Service utilization\"]\n    D[\"SYNDEMIC CLUSTERS<br>Nutritional Risks<br>Reproductive Risks<br>Healthcare-Access Risks\"]\n    E[\"OUTCOMES<br>Cumulative score (0-8)<br>Low, Medium, High burden\"]\n\n    A --> B\n    B --> C\n    C --> D\n    D --> E\n    E -.-> A\n```\n\nThe framework (adapted from Solar & Irwin, 2010 and Tsai, 2024) treats social determinants as upstream conditions that pattern multiple proximal risk domains. The feedback loop at the bottom represents the **biosocial nature** of syndemics: the accumulated health burden (outcomes) can reinforce and exacerbate the very structural and social inequalities that initially produced the risks.\n\n\n## Methods\n\n### Data Source and Study Population\n\nThe analysis utilized the 2022 Bangladesh Demographic and Health Survey (BDHS), a nationally representative cross-sectional survey [@niport2024bdhs]. The study population was restricted to ever-married women aged 15–49 who had a live birth in the three years preceding the survey to ensure the availability of maternal healthcare and decision-making indicators.\n\n```{mermaid}\ngraph TD\n    A[\"Ever-married women interviewed (15–49 years)<br/>(N = 30,344)\"]\n\n    E1[\"Excluded: No live birth in the 3 years<br/>preceding the survey (n = 18,687)\"]\n\n    B[\"<b>Analytic sample for descriptive statistics</b><br/>(n = 11,657)\"]\n\n    E2[\"Excluded: Missing values in multivariable<br/>model covariates (n = 4,031)\"]\n\n    C[\"<b>Final sample for multivariable modeling</b><br/>(n = 7,626)\"]\n\n    A --> B\n    A -.-> E1\n    B --> C\n    B -.-> E2\n\n    %% Styling\n    style B fill:#f0f7ff,stroke:#0056b3,stroke-width:2px\n    style C fill:#f4fff4,stroke:#2e7d32,stroke-width:2px\n```\n\nDue to the nature of survey skip patterns and item-level non-response, a complete-case approach requiring all nine risk indicators to be observed would have restricted the sample to 1,531 women (13.1% of those with recent births). To maintain population representativeness and statistical power, the primary analysis utilized an **available-indicator** cumulative score, including all 11,657 women for descriptive analysis and 7,626 women for the multivariable modeling where covariate data were complete.\n\n### Outcome and Risk Domains\n\nNine binary risk indicators were grouped into three functional domains to capture the multi-dimensional nature of the syndemic burden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Domain = c(\"Nutritional\", \"Reproductive health\", \"Healthcare access and autonomy\", \"**Total Syndemic Score**\"),\n  Indicators = c(\n    \"Underweight (BMI < 18.5); stunted height (< 145 cm)\",\n    \"Adolescent first birth (< 20y); high parity (> 4); short birth interval (< 24m); home delivery\",\n    \"Inadequate ANC (< 4 visits); distance to facility (major problem); low health autonomy\",\n    \"Sum of all nine binary indicators (dichotomized 0/1)\"\n  ),\n  `Score Range` = c(\"0–2\", \"0–4\", \"0–3\", \"**0–9**\")\n) |>\n  kable(caption = \"Syndemic risk domains, indicators, and score construction\", align = \"llc\", escape = FALSE)\n```\n\n::: {.cell-output-display}\n\n\nTable: Syndemic risk domains, indicators, and score construction\n\n|Domain                         |Indicators                                                                                     | Score Range |\n|:------------------------------|:----------------------------------------------------------------------------------------------|:-----------:|\n|Nutritional                    |Underweight (BMI < 18.5); stunted height (< 145 cm)                                            |     0–2     |\n|Reproductive health            |Adolescent first birth (< 20y); high parity (> 4); short birth interval (< 24m); home delivery |     0–4     |\n|Healthcare access and autonomy |Inadequate ANC (< 4 visits); distance to facility (major problem); low health autonomy         |     0–3     |\n|**Total Syndemic Score**       |Sum of all nine binary indicators (dichotomized 0/1)                                           |   **0–9**   |\n\n\n:::\n:::\n\n\nFor descriptive reporting and sensitivity analysis, the total score was collapsed into three ordered categories: **Low burden** (score 0), **Medium burden** (score 1–3), and **High burden** (score ≥ 4).\n\n### Covariates and Model Parameters\n\nMultivariable models included sociodemographic factors identified in the literature as key drivers of maternal and nutritional health in Bangladesh.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  `Variable Group` = c(\"Demographic\", \"Socioeconomic\", \"Geography\", \"Empowerment\"),\n  `Covariates (Levels)` = c(\n    \"Age group (15–24, 25–34, 35–49)\",\n    \"Respondent education (No education, Primary, Secondary, Higher); Wealth quintile (Poorest to Richest); Husband's education\",\n    \"Administrative Division (8 regions); Type of residence (Urban, Rural)\",\n    \"Employment status (Working, Not working)\"\n  ),\n  `Reference Category` = c(\"15–24 years\", \"Higher education; Richest quintile\", \"Dhaka Division; Urban residence\", \"Not working\")\n) |>\n  kable(caption = \"Covariates included in multivariable regression models\", align = \"lll\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Covariates included in multivariable regression models\n\n|Variable Group |Covariates (Levels)                                                                                                        |Reference Category                 |\n|:--------------|:--------------------------------------------------------------------------------------------------------------------------|:----------------------------------|\n|Demographic    |Age group (15–24, 25–34, 35–49)                                                                                            |15–24 years                        |\n|Socioeconomic  |Respondent education (No education, Primary, Secondary, Higher); Wealth quintile (Poorest to Richest); Husband's education |Higher education; Richest quintile |\n|Geography      |Administrative Division (8 regions); Type of residence (Urban, Rural)                                                      |Dhaka Division; Urban residence    |\n|Empowerment    |Employment status (Working, Not working)                                                                                   |Not working                        |\n\n\n:::\n:::\n\n\n### Statistical Analysis\n\nAll descriptive and regression analyses incorporated BDHS survey weights, strata, and primary sampling units using R's `survey` package [@lumley2004survey; @lumley2010complex].\n\n**Primary model:** Survey-weighted quasi-Poisson regression (`svyglm`, `family = quasipoisson`) for the raw syndemic score (0–8). The quasi-Poisson family was selected because the score is a bounded integer with mild overdispersion relative to a simple Poisson process (observed variance/mean ratio = 1.23; svyglm dispersion φ = 0.77; diagnostic weighted GLM φ = 1.08). Negative binomial regression was evaluated but yielded an equivalent fit (θ = 22.20), confirming that quasi-Poisson was sufficient. Results are reported as incidence rate ratios (IRR) with 95% confidence intervals [@hilbe2011negbin; @gardner1995regression].\n\n**Sensitivity analysis:** Ordinal proportional-odds logistic regression for low/medium/high burden categories [@mccullagh1980regression; @liu2016proportional]. The ordinal model provides a complementary perspective using the collapsed categorical outcome; its results are reported in the Supplementary Appendix.\n\n## Results\n\n### Risk Factor Prevalence\n\nThe chart below displays the percentage of women affected by each individual risk factor, grouped by their functional domain (Healthcare Access, Reproductive Health, and Nutritional).\n\nThe points represent the estimated percentage (prevalence) in the population, while the horizontal lines show the 95% confidence intervals (the range within which we are certain the true value lies). For instance, **Healthcare Access** risks are the most common, with over 60% of women receiving inadequate antenatal care. In contrast, **Nutritional** risks like underweight and stunted height affect approximately 10–12% of the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure1_risk_factor_prevalence.jpg\")\n```\n\n::: {.cell-output-display}\n![Weighted prevalence of individual risk factors across three syndemic domains.](figures/figure1_risk_factor_prevalence.jpg)\n:::\n:::\n\n\n### Syndemic Score Distribution\n\nThe distribution of the total syndemic score reveals the cumulative nature of risk among women in Bangladesh. While 24% of women have no identified risks, the majority (64.6%) experience between one and three concurrent risks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure2_syndemic_distribution.jpg\")\n```\n\n::: {.cell-output-display}\n![Distribution of total syndemic score (weighted, n = 11,657).](figures/figure2_syndemic_distribution.jpg)\n:::\n:::\n\n\n### Syndemic Burden Categories\n\nFor descriptive purposes, the syndemic score was collapsed into three ordinal categories representing the level of cumulative burden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburden_data <- read_csv(\"data/paper_burden_categories.csv\", show_col_types = FALSE)\n\nburden_data |>\n  transmute(\n    `Burden Level` = case_when(\n      str_detect(burden_category, \"Low\")    ~ \"Low Burden\",\n      str_detect(burden_category, \"Medium\") ~ \"Medium Burden\",\n      str_detect(burden_category, \"High\")   ~ \"High Burden\"\n    ),\n    `Score Range` = case_when(\n      str_detect(burden_category, \"Low\")    ~ \"0\",\n      str_detect(burden_category, \"Medium\") ~ \"1–3\",\n      str_detect(burden_category, \"High\")   ~ \"≥4\"\n    ),\n    `Unweighted n` = format(unweighted_n, big.mark = \",\"),\n    `Weighted Percentage (%)` = sprintf(\"%.1f%%\", weighted_percent)\n  ) |>\n  kable(\n    caption = \"Classification of women by syndemic burden category (n = 11,657)\",\n    align = \"llrr\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Classification of women by syndemic burden category (n = 11,657)\n\n|Burden Level  |Score Range | Unweighted n| Weighted Percentage (%)|\n|:-------------|:-----------|------------:|-----------------------:|\n|Low Burden    |0           |        2,860|                   24.0%|\n|Medium Burden |1–3         |        7,487|                   64.6%|\n|High Burden   |≥4          |        1,310|                   11.4%|\n\n\n:::\n:::\n\n\n### Sociodemographic and Geographic Patterning\n\nThe syndemic burden is strongly patterned by social determinants and geographic location. Mean syndemic scores across key demographic groups reveal significant disparities, particularly by education level and wealth quintile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure4_education_residence.jpg\")\n```\n\n::: {.cell-output-display}\n![Mean syndemic score by key demographics (95% CI).](figures/figure4_education_residence.jpg)\n:::\n:::\n\n\n#### Intersectionality: Wealth and Residence\n\nThe interaction of household wealth and urban-rural residence further identifies the most vulnerable populations. While higher wealth is protective in both settings, rural women in the lowest wealth quintiles experience a disproportionately high cumulative risk burden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure5_intersectionality_wealth_residence.jpg\")\n```\n\n::: {.cell-output-display}\n![Intersectionality of wealth and residence: mean syndemic score (95% CI).](figures/figure5_intersectionality_wealth_residence.jpg)\n:::\n:::\n\n\n#### Geographic Variation\n\nGeographically, the syndemic burden is not uniform across Bangladesh. Divisions such as Sylhet and Mymensingh exhibit higher average scores and a greater prevalence of high-burden cases compared to divisions like Dhaka or Khulna.\n\n![Geographic distribution of syndemic burden variation across Bangladesh.](figures/figure6_geographic_map.jpg){fig-alt=\"Geographic map of syndemic burden variation across Bangladesh by division.\"}\n\n### Multivariable Quasi-Poisson Regression (Primary Model)\n\nSurvey-weighted quasi-Poisson regression (φ = 0.77 from the full svyglm model; diagnostic weighted GLM φ = 1.08) was fit for the raw syndemic score. Results are incidence rate ratios (IRR): the multiplicative change in expected syndemic score per unit change in a predictor, holding all other variables constant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable3 <- read_csv(\"data/table3_quasipoisson_irr.csv\", show_col_types = FALSE)\n\ntable3 |>\n  mutate(variable_group = clean_variable_group(variable)) |>\n  transmute(\n    Group    = variable_group,\n    Category = category,\n    Reference = if_else(is.na(coefficient), \"✓\", \"\"),\n    `IRR (95% CI)` = IRR_CI,\n    `p-value`      = p_formatted\n  ) |>\n  kable(\n    caption = \"Table 3. Survey-weighted quasi-Poisson regression: predictors of syndemic burden score (n = 11,657)\",\n    align   = \"llcll\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 3. Survey-weighted quasi-Poisson regression: predictors of syndemic burden score (n = 11,657)\n\n|Group                |Category                      | Reference |IRR (95% CI)     |p-value |\n|:--------------------|:-----------------------------|:---------:|:----------------|:-------|\n|Age group            |15-24                         |     ✓     |1.00 (reference) |NA      |\n|Age group            |25-34                         |           |1.05 (1.01-1.08) |0.007   |\n|Age group            |35-49                         |           |1.14 (1.09-1.19) |<0.001  |\n|Respondent education |Higher                        |     ✓     |1.00 (reference) |NA      |\n|Respondent education |Secondary                     |           |1.68 (1.59-1.79) |<0.001  |\n|Respondent education |Primary                       |           |2.02 (1.88-2.16) |<0.001  |\n|Respondent education |No education                  |           |2.06 (1.90-2.23) |<0.001  |\n|Wealth quintile      |Richest                       |     ✓     |1.00 (reference) |NA      |\n|Wealth quintile      |Richer                        |           |1.16 (1.10-1.23) |<0.001  |\n|Wealth quintile      |Middle                        |           |1.24 (1.17-1.31) |<0.001  |\n|Wealth quintile      |Poorer                        |           |1.27 (1.18-1.36) |<0.001  |\n|Wealth quintile      |Poorest                       |           |1.39 (1.30-1.49) |<0.001  |\n|Residence            |Urban                         |     ✓     |1.00 (reference) |NA      |\n|Residence            |Rural                         |           |1.11 (1.06-1.16) |<0.001  |\n|Division             |Dhaka                         |     ✓     |1.00 (reference) |NA      |\n|Division             |Barishal                      |           |1.08 (1.00-1.16) |0.043   |\n|Division             |Chattogram                    |           |1.10 (1.02-1.17) |0.008   |\n|Division             |Khulna                        |           |1.02 (0.95-1.10) |0.526   |\n|Division             |Mymensingh                    |           |1.07 (1.01-1.15) |0.033   |\n|Division             |Rajshahi                      |           |1.06 (0.99-1.13) |0.112   |\n|Division             |Rangpur                       |           |1.03 (0.96-1.11) |0.423   |\n|Division             |Sylhet                        |           |1.09 (1.01-1.17) |0.026   |\n|Employment           |Not working                   |     ✓     |1.00 (reference) |NA      |\n|Employment           |Working                       |           |0.94 (0.91-0.98) |0.002   |\n|Employment           |Not reported / not applicable |           |0.39 (0.34-0.44) |<0.001  |\n|Husband's education  |Higher                        |     ✓     |1.00 (reference) |NA      |\n|Husband's education  |Secondary                     |           |1.08 (1.01-1.14) |0.015   |\n|Husband's education  |Primary                       |           |1.14 (1.08-1.22) |<0.001  |\n|Husband's education  |No education                  |           |1.14 (1.07-1.22) |<0.001  |\n|Husband's education  |Not reported / not applicable |           |0.89 (0.78-1.02) |0.107   |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_data <- table3 |>\n  filter(!is.na(coefficient)) |>\n  mutate(\n    variable_group = clean_variable_group(variable),\n    predictor      = paste0(variable_group, \": \", category),\n    direction      = if_else(IRR < 1, \"Protective\", \"Risk\"),\n    predictor      = factor(predictor, levels = predictor[order(IRR)])\n  )\n\nggplot(forest_data, aes(x = IRR, y = predictor, color = direction)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray45\") +\n  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0.22, linewidth = 0.8) +\n  geom_point(size = 2.8) +\n  scale_x_log10() +\n  scale_color_manual(values = c(\"Protective\" = \"#1b9e77\", \"Risk\" = \"#d95f02\")) +\n  labs(x = \"Incidence Rate Ratio (log scale)\", y = NULL, color = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.\nℹ Please use the `orientation` argument of `geom_errorbar()` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`height` was translated to `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Full-model IRRs and 95% confidence intervals from quasi-Poisson regression. IRR < 1 indicates a lower expected syndemic score relative to the reference category.](index_files/figure-html/forest-plot-full-model-1.png){width=864}\n:::\n:::\n\n\nThe full model revealed strong social gradients. Compared with women with higher education, those with no education had 2.06 times the expected syndemic score (IRR 2.06, 95% CI 1.90–2.23). Rural residence was associated with an 11% higher score (IRR 1.11, 95% CI 1.06–1.16). Women in the poorest wealth quintile had 39% higher scores than the richest (IRR 1.39, 95% CI 1.30–1.49). Working women had modestly lower scores (IRR 0.94, 95% CI 0.91–0.98). Husband's education showed an independent gradient: no education versus higher (IRR 1.14, 95% CI 1.07–1.22).\n\n### Interaction and Sensitivity Checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsocial_interactions <- read_csv(\"data/paper_social_interaction_tests.csv\", show_col_types = FALSE)\n\nsocial_interactions |>\n  transmute(\n    Test         = test,\n    `F statistic` = sprintf(\"%.2f\", statistic),\n    `p-value`    = p_formatted\n  ) |>\n  kable(caption = \"Ordinal model interaction tests (education × residence; wealth × residence)\", align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Ordinal model interaction tests (education × residence; wealth × residence)\n\n|Test                                 | F statistic| p-value|\n|:------------------------------------|-----------:|-------:|\n|Ordinal model: wealth x residence    |        0.17|   0.952|\n|Ordinal model: education x residence |        0.59|   0.621|\n\n\n:::\n:::\n\n\nThe interaction tests do not support statistical effect modification by residence for either wealth or education, indicating the evidence is stronger for broad social patterning than for subgroup-specific slopes.\n\n## Discussion\n\n### Principal Findings\n\nThis study found that co-occurring risks are common among women in Bangladesh. Most women had at least one risk, nearly two-thirds were in the medium-burden category, and 11.4% had high burden. Access/autonomy and reproductive-health risks were more common than nutritional risks, but all three domains co-occurred at a rate 23% higher than expected under independence.\n\nThe strongest and most consistent predictors were education and wealth. Women with no education had twice the expected syndemic score relative to women with higher education (IRR 2.06). Rural residence independently increased scores by 11%. Husband's education remained independently predictive, consistent with a household-level interpretation of social advantage.\n\n### Interpretation in Light of Prior Evidence\n\nThe results align with prior Bangladesh studies showing socioeconomic gradients in women's undernutrition [@rahman2022undernutrition; @hossain2023doubleburden], reproductive timing [@islam2021childmarriage], and maternal healthcare utilization [@yaya2017delivery; @khan2022continuum; @haider2017autonomy]. The contribution here is to show that these risks are not isolated — they cluster across domains and are patterned by the same social determinants.\n\nThe findings also reflect the methodological caution recommended in recent syndemic literature [@tsai2018syndemics; @bulled2024guide]. The score captures cumulative burden and modest clustering, but true syndemic synergy would require a downstream health outcome independent of the component risks, or longitudinal evidence of interacting pathways. The quasi-Poisson count model was selected as the primary model because it retains the full information in the score distribution, produces directly interpretable IRRs, and appropriately handles the mild overdispersion present in the data.\n\n### Policy Implications\n\nThe results point toward integrated interventions rather than single-risk programs. Education, household socioeconomic position, rural service access, ANC coverage, and women's decision-making autonomy are linked domains. Programs addressing maternal nutrition, reproductive health, and service access together may better match the pattern of co-occurring risk observed in the data.\n\n### Strengths and Limitations\n\nStrengths include nationally representative BDHS 2022 data, survey-weighted estimation throughout, a clearly defined multidomain burden score, explicit clustering checks, a primary count model with sensitivity analysis, and transparent reporting of model diagnostics.\n\nLimitations are important. The cross-sectional design prevents causal inference. Several indicators are subgroup-specific or missing for subsets of women, so the score is based on available indicators rather than complete observation of all nine risks. The analysis tests clustering and social patterning more directly than biological or causal synergy.\n\n## Conclusion\n\nBDHS 2022 evidence shows that nutritional, reproductive-health, and healthcare-access/autonomy risks cluster among Bangladeshi women and are strongly socially patterned. The most defensible interpretation is a cumulative syndemic-burden framework: the burden is multidomain, socially structured, and policy-relevant, but claims of causal synergy should remain cautious until tested with longitudinal data or independent downstream health outcomes.\n\n## Supplementary Appendix\n\n### S1. Sample Characteristics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 <- read_csv(\"data/table1_sample_characteristics.csv\", show_col_types = FALSE)\n\ntable1 |>\n  kable(\n    caption = \"Table 1. Sample characteristics (n = 11,657 women with recent births, BDHS 2022)\",\n    align = \"lrr\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Sample characteristics (n = 11,657 women with recent births, BDHS 2022)\n\n|variable          |     category|     n|weighted_percent |  ci_lower|  ci_upper|percent_ci       |          variable_label|\n|:-----------------|------------:|-----:|:----------------|---------:|---------:|:----------------|-----------------------:|\n|age               | Mean (years)| 11657|NA               |        NA|        NA|26.7 (26.6–26.9) |             Age (years)|\n|age_group         |        15–24|  4552|40.023328        | 38.930093| 41.116563|40.0 (38.9–41.1) |               Age group|\n|age_group         |        25–34|  5686|48.057783        | 46.989222| 49.126343|48.1 (47.0–49.1) |               Age group|\n|age_group         |        35–49|  1419|11.918889        | 11.199661| 12.638117|11.9 (11.2–12.6) |               Age group|\n|education         |           No|   707|6.068668         |  5.333091|  6.804246|6.1 (5.3–6.8)    |         Education level|\n|education         |      Primary|  2690|22.692787        | 21.503959| 23.881615|22.7 (21.5–23.9) |         Education level|\n|education         |    Secondary|  6075|53.624782        | 52.296227| 54.953338|53.6 (52.3–55.0) |         Education level|\n|education         |       Higher|  2185|17.613762        | 16.356178| 18.871347|17.6 (16.4–18.9) |         Education level|\n|wealth            |      Poorest|  2467|20.839595        | 19.386835| 22.292355|20.8 (19.4–22.3) |         Wealth quintile|\n|wealth            |       Poorer|  2300|20.240692        | 19.084560| 21.396824|20.2 (19.1–21.4) |         Wealth quintile|\n|wealth            |       Middle|  2283|20.255083        | 19.088045| 21.422121|20.3 (19.1–21.4) |         Wealth quintile|\n|wealth            |       Richer|  2281|19.599175        | 18.339607| 20.858744|19.6 (18.3–20.9) |         Wealth quintile|\n|wealth            |      Richest|  2326|19.065455        | 17.292520| 20.838390|19.1 (17.3–20.8) |         Wealth quintile|\n|residence         |        Urban|  3950|27.770917        | 26.303769| 29.238065|27.8 (26.3–29.2) |          Residence type|\n|residence         |        Rural|  7707|72.229083        | 70.761935| 73.696231|72.2 (70.8–73.7) |          Residence type|\n|division          |     Barishal|  1311|6.440109         |  5.886354|  6.993864|6.4 (5.9–7.0)    | Administrative division|\n|division          |   Chattogram|  1932|20.898781        | 19.343053| 22.454508|20.9 (19.3–22.5) | Administrative division|\n|division          |        Dhaka|  1793|25.548923        | 24.152996| 26.944850|25.5 (24.2–26.9) | Administrative division|\n|division          |       Khulna|  1333|10.460425        |  9.760769| 11.160082|10.5 (9.8–11.2)  | Administrative division|\n|division          |   Mymensingh|  1353|8.236174         |  7.699554|  8.772794|8.2 (7.7–8.8)    | Administrative division|\n|division          |     Rajshahi|  1218|10.757006        |  9.787137| 11.726875|10.8 (9.8–11.7)  | Administrative division|\n|division          |      Rangpur|  1382|11.343060        | 10.598741| 12.087379|11.3 (10.6–12.1) | Administrative division|\n|division          |       Sylhet|  1335|6.315522         |  5.901995|  6.729049|6.3 (5.9–6.7)    | Administrative division|\n|employment        |  Not working|  5786|73.622731        | 72.060112| 75.185349|73.6 (72.1–75.2) |       Employment status|\n|employment        |      Working|  1966|26.377269        | 24.814651| 27.939888|26.4 (24.8–27.9) |       Employment status|\n|husband_education | No education|  1171|15.524582        | 14.322285| 16.726880|15.5 (14.3–16.7) |     Husband's education|\n|husband_education |      Primary|  2302|30.049254        | 28.573087| 31.525422|30.0 (28.6–31.5) |     Husband's education|\n|husband_education |    Secondary|  2626|35.256231        | 33.803964| 36.708498|35.3 (33.8–36.7) |     Husband's education|\n|husband_education |       Higher|  1527|19.169932        | 17.645750| 20.694114|19.2 (17.6–20.7) |     Husband's education|\n\n\n:::\n:::\n\n\n### S2. Domain Co-occurrence and Clustering\n\nEvidence for the clustering of risk indicators and functional domains was assessed via a correlation matrix and an observed-versus-expected (O/E) analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure3_correlation_heatmap.jpg\")\n```\n\n::: {.cell-output-display}\n![Pairwise correlation matrix of nine risk indicators.](figures/figure3_correlation_heatmap.jpg)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndomain_oe <- read_csv(\"data/paper_domain_observed_expected.csv\", show_col_types = FALSE)\n\ndomain_oe |>\n  transmute(\n    `Domain combination`     = clustering_test,\n    `Observed %`             = sprintf(\"%.1f\", observed_pct),\n    `Expected % (independence)` = sprintf(\"%.1f\", expected_pct_under_independence),\n    `O/E ratio`              = sprintf(\"%.2f\", observed_expected_ratio),\n    `95% CI (observed)`      = sprintf(\"%.1f–%.1f\", ci_lower_pct, ci_upper_pct)\n  ) |>\n  kable(\n    caption = \"Observed versus expected co-occurrence of risk domains under independence\",\n    align = \"lrrrr\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Observed versus expected co-occurrence of risk domains under independence\n\n|Domain combination             | Observed %| Expected % (independence)| O/E ratio| 95% CI (observed)|\n|:------------------------------|----------:|-------------------------:|---------:|-----------------:|\n|Nutrition + reproductive       |       13.7|                      12.5|      1.10|         12.5–15.0|\n|Nutrition + access/autonomy    |       16.9|                      15.3|      1.10|         15.5–18.2|\n|Reproductive + access/autonomy |       47.2|                      44.8|      1.05|         45.1–49.2|\n|All three domains              |       11.4|                       9.3|      1.23|         10.2–12.6|\n\n\n:::\n:::\n\n\nAll three risk domains co-occurred at a rate 1.23 times higher than expected under the independence assumption, providing evidence of clustering across nutritional, reproductive-health, and access/autonomy domains.\n\n### S3. Model Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiag <- read_csv(\"data/quasipoisson_model_diagnostics.csv\", show_col_types = FALSE)\n\ndiag |>\n  transmute(\n    Metric = metric,\n    Value  = as.character(round(as.numeric(value), 4)),\n    Note   = note\n  ) |>\n  kable(caption = \"S3. Quasi-Poisson model diagnostics\", align = \"lll\")\n```\n\n::: {.cell-output-display}\n\n\nTable: S3. Quasi-Poisson model diagnostics\n\n|Metric                                   |Value   |Note                                                                                                            |\n|:----------------------------------------|:-------|:---------------------------------------------------------------------------------------------------------------|\n|n_complete                               |11657   |Complete cases after recoding blank employment and husband education.                                           |\n|syndemic_score_min                       |0       |Integer count check.                                                                                            |\n|syndemic_score_max                       |8       |Observed maximum; theoretical maximum is 9.                                                                     |\n|raw_mean                                 |1.6322  |Unweighted mean.                                                                                                |\n|raw_variance                             |2.0081  |Unweighted variance.                                                                                            |\n|raw_variance_mean_ratio                  |1.2304  |Unweighted variance divided by unweighted mean.                                                                 |\n|svyglm_quasipoisson_phi                  |0.7699  |Final design-based quasi-Poisson dispersion from svyglm full model.                                             |\n|diagnostic_weighted_glm_quasipoisson_phi |1.0843  |Comparable exploratory weighted GLM dispersion from the age, education, wealth, and residence diagnostic model. |\n|observed_zero_percent                    |24.0144 |Survey-weighted percentage with syndemic_score == 0.                                                            |\n|poisson_expected_zero_percent            |27.0694 |Survey-weighted expected zero percentage from Poisson svyglm.                                                   |\n|negative_binomial_expected_zero_percent  |22.8828 |Weighted expected zero percentage from diagnostic NB model.                                                     |\n|negative_binomial_theta                  |22.5791 |Negative binomial diagnostic used a simpler model because full survey NB is not available in svyglm.            |\n\n\n:::\n:::\n\n\n### S4. Ordinal Sensitivity Analysis — Full Results\n\nThe ordinal proportional-odds model uses the same predictors and the same burden categories (Low 0 / Medium 1–3 / High ≥4) as the primary analysis. Results are odds ratios (OR) for being in a higher burden category, with **no education**, **poorest wealth quintile**, **urban residence**, and **Barishal division** as reference categories. The ordinal model is supplementary; its role is to confirm the direction and significance of predictors found in the primary quasi-Poisson model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nordinal_sens <- read_csv(\"data/paper_ordinal_sensitivity_results.csv\", show_col_types = FALSE)\n\nordinal_sens |>\n  mutate(\n    Group = case_when(\n      str_starts(term, \"husband_education\") ~ \"Husband's education\",\n      str_starts(term, \"age_group\")         ~ \"Age group\",\n      str_starts(term, \"education\")         ~ \"Respondent education\",\n      str_starts(term, \"wealth\")            ~ \"Wealth quintile\",\n      str_starts(term, \"residence\")         ~ \"Residence\",\n      str_starts(term, \"division\")          ~ \"Division\",\n      str_starts(term, \"employment\")        ~ \"Employment\",\n      TRUE                                  ~ term\n    ),\n    Category = case_when(\n      str_starts(term, \"husband_education\") ~ str_remove(term, \"husband_education\"),\n      str_starts(term, \"age_group\")         ~ str_remove(term, \"age_group\"),\n      str_starts(term, \"education\")         ~ str_remove(term, \"education\"),\n      str_starts(term, \"wealth\")            ~ str_remove(term, \"wealth\"),\n      str_starts(term, \"residence\")         ~ str_remove(term, \"residence\"),\n      str_starts(term, \"division\")          ~ str_remove(term, \"division\"),\n      str_starts(term, \"employment\")        ~ str_remove(term, \"employment\"),\n      TRUE                                  ~ term\n    )\n  ) |>\n  transmute(\n    Group,\n    Category,\n    `OR (95% CI)` = OR_CI,\n    `p-value`     = p_formatted\n  ) |>\n  kable(caption = \"S4. Ordinal logistic sensitivity analysis: odds ratios for elevated syndemic burden\", align = \"llll\")\n```\n\n::: {.cell-output-display}\n\n\nTable: S4. Ordinal logistic sensitivity analysis: odds ratios for elevated syndemic burden\n\n|Group                        |Category                     |OR (95% CI)      |p-value |\n|:----------------------------|:----------------------------|:----------------|:-------|\n|Age group                    |25-34                        |0.99 (0.87-1.14) |0.936   |\n|Age group                    |35-49                        |1.13 (0.94-1.34) |0.191   |\n|Respondent education         |Primary                      |0.88 (0.69-1.11) |0.288   |\n|Respondent education         |Secondary                    |0.53 (0.41-0.68) |<0.001  |\n|Respondent education         |Higher                       |0.22 (0.16-0.30) |<0.001  |\n|Wealth quintile              |Poorer                       |0.77 (0.64-0.92) |0.005   |\n|Wealth quintile              |Middle                       |0.69 (0.57-0.84) |<0.001  |\n|Wealth quintile              |Richer                       |0.60 (0.49-0.73) |<0.001  |\n|Wealth quintile              |Richest                      |0.40 (0.31-0.51) |<0.001  |\n|Residence                    |Rural                        |1.37 (1.17-1.59) |<0.001  |\n|Division                     |Chattogram                   |1.10 (0.80-1.50) |0.560   |\n|Division                     |Dhaka                        |0.74 (0.57-0.95) |0.019   |\n|Division                     |Khulna                       |0.81 (0.60-1.08) |0.150   |\n|Division                     |Mymensingh                   |0.95 (0.72-1.25) |0.709   |\n|Division                     |Rajshahi                     |0.94 (0.71-1.25) |0.678   |\n|Division                     |Rangpur                      |0.81 (0.61-1.08) |0.147   |\n|Division                     |Sylhet                       |1.14 (0.85-1.54) |0.379   |\n|Employment                   |Working                      |0.81 (0.72-0.92) |<0.001  |\n|Husband's education          |Primary                      |0.88 (0.73-1.07) |0.199   |\n|Husband's education          |Secondary                    |0.72 (0.59-0.88) |0.001   |\n|Husband's education          |Higher                       |0.52 (0.40-0.67) |<0.001  |\n|Low (0)&#124;Medium (1-3)    |Low (0)&#124;Medium (1-3)    |0.03 (0.02-0.04) |<0.001  |\n|Medium (1-3)&#124;High (>=4) |Medium (1-3)&#124;High (>=4) |1.73 (1.23-2.45) |0.002   |\n\n\n:::\n:::\n\n\n### S5. Missingness Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissingness <- read_csv(\"data/paper_missingness_summary.csv\", show_col_types = FALSE)\n\nmissingness |>\n  transmute(\n    Variable        = variable,\n    `Total N`       = format(n_total, big.mark = \",\"),\n    `Missing`       = format(n_missing, big.mark = \",\"),\n    `Non-missing`   = format(n_nonmissing, big.mark = \",\"),\n    `Missing %`     = pct1(missing_percent)\n  ) |>\n  kable(caption = \"S5. Missingness summary for risk indicators and model covariates\", align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: S5. Missingness summary for risk indicators and model covariates\n\n|Variable          | Total N| Missing| Non-missing| Missing %|\n|:-----------------|-------:|-------:|-----------:|---------:|\n|underweight       |  11,657|   7,776|       3,881|     66.7%|\n|stunted_height    |  11,657|   7,777|       3,880|     66.7%|\n|high_parity       |  11,657|       0|      11,657|      0.0%|\n|adolescent_birth  |  11,657|       0|      11,657|      0.0%|\n|short_interval    |  11,657|   4,182|       7,475|     35.9%|\n|home_delivery     |  11,657|   6,672|       4,985|     57.2%|\n|distance_problem  |  11,657|   3,905|       7,752|     33.5%|\n|low_autonomy      |  11,657|   4,017|       7,640|     34.5%|\n|inadequate_anc    |  11,657|   6,673|       4,984|     57.2%|\n|syndemic_score    |  11,657|       0|      11,657|      0.0%|\n|syndemic_tertile  |  11,657|       0|      11,657|      0.0%|\n|age_group         |  11,657|       0|      11,657|      0.0%|\n|education         |  11,657|       0|      11,657|      0.0%|\n|wealth            |  11,657|       0|      11,657|      0.0%|\n|residence         |  11,657|       0|      11,657|      0.0%|\n|division          |  11,657|       0|      11,657|      0.0%|\n|employment        |  11,657|   3,905|       7,752|     33.5%|\n|husband_education |  11,657|   4,031|       7,626|     34.6%|\n\n\n:::\n:::\n\n\n### S6. Available-Indicator vs Complete-Case Score Sensitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomplete_case <- read_csv(\"data/paper_complete_case_sensitivity.csv\", show_col_types = FALSE)\n\ncomplete_case |>\n  transmute(\n    Analysis             = analysis,\n    `Burden category`    = category,\n    `Weighted n`         = format(round(weighted_n), big.mark = \",\"),\n    `Weighted %`         = pct1(weighted_percent)\n  ) |>\n  kable(caption = \"S6. Available-indicator vs complete 9-indicator burden distribution\", align = \"llrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: S6. Available-indicator vs complete 9-indicator burden distribution\n\n|Analysis                   |Burden category | Weighted n| Weighted %|\n|:--------------------------|:---------------|----------:|----------:|\n|Available-indicator score  |Low (0)         |      2,817|      24.0%|\n|Available-indicator score  |Medium (1-3)    |      7,571|      64.6%|\n|Available-indicator score  |High (>=4)      |      1,341|      11.4%|\n|Complete 9-indicator score |Low (0)         |         88|       5.7%|\n|Complete 9-indicator score |Medium (1-3)    |        921|      59.6%|\n|Complete 9-indicator score |High (>=4)      |        537|      34.7%|\n\n\n:::\n:::\n\n\n### S7. Very High Burden by Division (score ≥6)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvery_high_division <- read_csv(\"data/paper_division_very_high_ge6.csv\", show_col_types = FALSE)\n\nvery_high_division |>\n  transmute(\n    Division = division,\n    `Very high burden, score ≥6` = prev_ci\n  ) |>\n  kable(caption = \"S7. Very high syndemic burden (score ≥6) by division\", align = \"ll\")\n```\n\n::: {.cell-output-display}\n\n\nTable: S7. Very high syndemic burden (score ≥6) by division\n\n|Division   |Very high burden, score ≥6 |\n|:----------|:--------------------------|\n|Sylhet     |2.4% (1.5-3.2)             |\n|Mymensingh |1.8% (1.0-2.6)             |\n|Rajshahi   |1.2% (0.3-2.0)             |\n|Chattogram |1.1% (0.5-1.7)             |\n|Rangpur    |1.0% (0.4-1.6)             |\n|Barishal   |0.9% (0.3-1.6)             |\n|Khulna     |0.4% (0.0-0.7)             |\n|Dhaka      |0.3% (0.0-0.5)             |\n\n\n:::\n:::\n\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}