{
  "hash": "52ba7b33e0e9b52f1c523c57ef5e9b99",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Results\"\n---\n\n\n\n## Risk Factor Prevalence\n\nThe chart below displays the percentage of women affected by each individual risk factor, grouped by their functional domain (Healthcare Access, Reproductive Health, and Nutritional).\n\nThe points represent the estimated percentage (prevalence) in the population, while the horizontal lines show the 95% confidence intervals (the range within which we are certain the true value lies). For instance, **Healthcare Access** risks are the most common, with over 60% of women receiving inadequate antenatal care. In contrast, **Nutritional** risks like underweight and stunted height affect approximately 10–12% of the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure1_risk_factor_prevalence.jpg\")\n```\n\n::: {.cell-output-display}\n![Weighted prevalence of individual risk factors across three syndemic domains.](figures/figure1_risk_factor_prevalence.jpg)\n:::\n:::\n\n\n## Syndemic Score Distribution\n\nThe distribution of the total syndemic score reveals the cumulative nature of risk among women in Bangladesh. While 24% of women have no identified risks, the majority (64.6%) experience between one and three concurrent risks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure2_syndemic_distribution.jpg\")\n```\n\n::: {.cell-output-display}\n![Distribution of total syndemic score (weighted, n = 11,657).](figures/figure2_syndemic_distribution.jpg)\n:::\n:::\n\n\n## Syndemic Burden Categories\n\nFor descriptive purposes, the syndemic score was collapsed into three ordinal categories representing the level of cumulative burden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburden_data <- read_csv(\"data/paper_burden_categories.csv\", show_col_types = FALSE)\n\nburden_data |>\n  transmute(\n    `Burden Level` = case_when(\n      str_detect(burden_category, \"Low\")    ~ \"Low Burden\",\n      str_detect(burden_category, \"Medium\") ~ \"Medium Burden\",\n      str_detect(burden_category, \"High\")   ~ \"High Burden\"\n    ),\n    `Score Range` = case_when(\n      str_detect(burden_category, \"Low\")    ~ \"0\",\n      str_detect(burden_category, \"Medium\") ~ \"1–3\",\n      str_detect(burden_category, \"High\")   ~ \"≥4\"\n    ),\n    `Unweighted n` = format(unweighted_n, big.mark = \",\"),\n    `Weighted Percentage (%)` = sprintf(\"%.1f%%\", weighted_percent)\n  ) |>\n  kable(\n    caption = \"Classification of women by syndemic burden category (n = 11,657)\",\n    align = \"llrr\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Classification of women by syndemic burden category (n = 11,657)\n\n|Burden Level  |Score Range | Unweighted n| Weighted Percentage (%)|\n|:-------------|:-----------|------------:|-----------------------:|\n|Low Burden    |0           |        2,860|                   24.0%|\n|Medium Burden |1–3         |        7,487|                   64.6%|\n|High Burden   |≥4          |        1,310|                   11.4%|\n\n\n:::\n:::\n\n\n## Sociodemographic and Geographic Patterning\n\nThe syndemic burden is strongly patterned by social determinants and geographic location. Mean syndemic scores across key demographic groups reveal significant disparities, particularly by education level and wealth quintile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure4_education_residence.jpg\")\n```\n\n::: {.cell-output-display}\n![Mean syndemic score by key demographics (95% CI).](figures/figure4_education_residence.jpg)\n:::\n:::\n\n\n### Intersectionality: Wealth and Residence\n\nThe interaction of household wealth and urban-rural residence further identifies the most vulnerable populations. While higher wealth is protective in both settings, rural women in the lowest wealth quintiles experience a disproportionately high cumulative risk burden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"figures/figure5_intersectionality_wealth_residence.jpg\")\n```\n\n::: {.cell-output-display}\n![Intersectionality of wealth and residence: mean syndemic score (95% CI).](figures/figure5_intersectionality_wealth_residence.jpg)\n:::\n:::\n\n\n### Geographic Variation\n\nGeographically, the syndemic burden is not uniform across Bangladesh. Divisions such as Sylhet and Mymensingh exhibit higher average scores and a greater prevalence of high-burden cases compared to divisions like Dhaka or Khulna.\n\n![Geographic distribution of syndemic burden variation across Bangladesh.](figures/figure6_geographic_map.jpg){fig-alt=\"Geographic map of syndemic burden variation across Bangladesh by division.\"}\n\n## Multivariable Quasi-Poisson Regression (Primary Model)\n\nSurvey-weighted quasi-Poisson regression (φ = 0.77 from the full svyglm model; diagnostic weighted GLM φ = 1.08) was fit for the raw syndemic score. Results are incidence rate ratios (IRR): the multiplicative change in expected syndemic score per unit change in a predictor, holding all other variables constant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable3 <- read_csv(\"data/table3_quasipoisson_irr.csv\", show_col_types = FALSE)\n\ntable3 |>\n  mutate(variable_group = clean_variable_group(variable)) |>\n  transmute(\n    Group    = variable_group,\n    Category = category,\n    Reference = if_else(is.na(coefficient), \"✓\", \"\"),\n    `IRR (95% CI)` = IRR_CI,\n    `p-value`      = p_formatted\n  ) |>\n  kable(\n    caption = \"Table 3. Survey-weighted quasi-Poisson regression: predictors of syndemic burden score (n = 11,657)\",\n    align   = \"llcll\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 3. Survey-weighted quasi-Poisson regression: predictors of syndemic burden score (n = 11,657)\n\n|Group                |Category                      | Reference |IRR (95% CI)     |p-value |\n|:--------------------|:-----------------------------|:---------:|:----------------|:-------|\n|Age group            |15-24                         |     ✓     |1.00 (reference) |NA      |\n|Age group            |25-34                         |           |1.05 (1.01-1.08) |0.007   |\n|Age group            |35-49                         |           |1.14 (1.09-1.19) |<0.001  |\n|Respondent education |Higher                        |     ✓     |1.00 (reference) |NA      |\n|Respondent education |Secondary                     |           |1.68 (1.59-1.79) |<0.001  |\n|Respondent education |Primary                       |           |2.02 (1.88-2.16) |<0.001  |\n|Respondent education |No education                  |           |2.06 (1.90-2.23) |<0.001  |\n|Wealth quintile      |Richest                       |     ✓     |1.00 (reference) |NA      |\n|Wealth quintile      |Richer                        |           |1.16 (1.10-1.23) |<0.001  |\n|Wealth quintile      |Middle                        |           |1.24 (1.17-1.31) |<0.001  |\n|Wealth quintile      |Poorer                        |           |1.27 (1.18-1.36) |<0.001  |\n|Wealth quintile      |Poorest                       |           |1.39 (1.30-1.49) |<0.001  |\n|Residence            |Urban                         |     ✓     |1.00 (reference) |NA      |\n|Residence            |Rural                         |           |1.11 (1.06-1.16) |<0.001  |\n|Division             |Dhaka                         |     ✓     |1.00 (reference) |NA      |\n|Division             |Barishal                      |           |1.08 (1.00-1.16) |0.043   |\n|Division             |Chattogram                    |           |1.10 (1.02-1.17) |0.008   |\n|Division             |Khulna                        |           |1.02 (0.95-1.10) |0.526   |\n|Division             |Mymensingh                    |           |1.07 (1.01-1.15) |0.033   |\n|Division             |Rajshahi                      |           |1.06 (0.99-1.13) |0.112   |\n|Division             |Rangpur                       |           |1.03 (0.96-1.11) |0.423   |\n|Division             |Sylhet                        |           |1.09 (1.01-1.17) |0.026   |\n|Employment           |Not working                   |     ✓     |1.00 (reference) |NA      |\n|Employment           |Working                       |           |0.94 (0.91-0.98) |0.002   |\n|Employment           |Not reported / not applicable |           |0.39 (0.34-0.44) |<0.001  |\n|Husband's education  |Higher                        |     ✓     |1.00 (reference) |NA      |\n|Husband's education  |Secondary                     |           |1.08 (1.01-1.14) |0.015   |\n|Husband's education  |Primary                       |           |1.14 (1.08-1.22) |<0.001  |\n|Husband's education  |No education                  |           |1.14 (1.07-1.22) |<0.001  |\n|Husband's education  |Not reported / not applicable |           |0.89 (0.78-1.02) |0.107   |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_data <- table3 |>\n  filter(!is.na(coefficient)) |>\n  mutate(\n    variable_group = clean_variable_group(variable),\n    predictor      = paste0(variable_group, \": \", category),\n    direction      = if_else(IRR < 1, \"Protective\", \"Risk\"),\n    predictor      = factor(predictor, levels = predictor[order(IRR)])\n  )\n\nggplot(forest_data, aes(x = IRR, y = predictor, color = direction)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray45\") +\n  geom_errorbarh(aes(xmin = CI_lower, xmax = CI_upper), height = 0.22, linewidth = 0.8) +\n  geom_point(size = 2.8) +\n  scale_x_log10() +\n  scale_color_manual(values = c(\"Protective\" = \"#1b9e77\", \"Risk\" = \"#d95f02\")) +\n  labs(x = \"Incidence Rate Ratio (log scale)\", y = NULL, color = NULL) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.\nℹ Please use the `orientation` argument of `geom_errorbar()` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`height` was translated to `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Full-model IRRs and 95% confidence intervals from quasi-Poisson regression. IRR < 1 indicates a lower expected syndemic score relative to the reference category.](results_files/figure-html/forest-plot-full-model-1.png){width=864}\n:::\n:::\n\n\nThe full model revealed strong social gradients. Compared with women with higher education, those with no education had 2.06 times the expected syndemic score (IRR 2.06, 95% CI 1.90–2.23). Rural residence was associated with an 11% higher score (IRR 1.11, 95% CI 1.06–1.16). Women in the poorest wealth quintile had 39% higher scores than the richest (IRR 1.39, 95% CI 1.30–1.49). Working women had modestly lower scores (IRR 0.94, 95% CI 0.91–0.98). Husband's education showed an independent gradient: no education versus higher (IRR 1.14, 95% CI 1.07–1.22).\n\n## Interaction and Sensitivity Checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsocial_interactions <- read_csv(\"data/paper_social_interaction_tests.csv\", show_col_types = FALSE)\n\nsocial_interactions |>\n  transmute(\n    Test         = test,\n    `F statistic` = sprintf(\"%.2f\", statistic),\n    `p-value`    = p_formatted\n  ) |>\n  kable(caption = \"Ordinal model interaction tests (education × residence; wealth × residence)\", align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Ordinal model interaction tests (education × residence; wealth × residence)\n\n|Test                                 | F statistic| p-value|\n|:------------------------------------|-----------:|-------:|\n|Ordinal model: wealth x residence    |        0.17|   0.952|\n|Ordinal model: education x residence |        0.59|   0.621|\n\n\n:::\n:::\n\n\nThe interaction tests do not support statistical effect modification by residence for either wealth or education, indicating the evidence is stronger for broad social patterning than for subgroup-specific slopes.\n",
    "supporting": [
      "results_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}